language: c++
sudo: false
matrix:
  include:
#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          sources:
#            - ubuntu-toolchain-r-test
#            - llvm-toolchain-precise
#            - llvm-toolchain-precise-3.7
#          packages:
#            - clang-3.8
#            - g++-6
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
cache:
  apt: true
  directories:
  - ".travis/cmake/build/install"
  - ".travis/boost-install"

before_install:
  - if [ "$CC"  == "gcc"     ]; then export CC=gcc-6; fi
  - if [ "$CXX" == "g++"     ]; then export CXX=g++-6; fi
  - if [ "$CC"  == "clang"   ]; then export CC=clang-3.8; fi
  - if [ "$CXX" == "clang++" ]; then export CXX=clang++-3.8; fi
  - pushd . && source "./update-cmake.sh"                             && popd
  - pushd . && source "./update-boost.sh" --with-locale --with-system && popd

script:
  - cmake --version
  - $CC --version
  - $CXX --version

notifications:
  email: false
