language: c++
compiler:
  - clang
#  - gcc

sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

before_install:
  - if [ "$CC"  == "gcc" ]; then export CC=gcc-5; fi
  - if [ "$CXX" == "g++" ]; then export CXX=g++-5; fi
  - pushd . && source "./install-biicode.sh"  && popd
  - bii setup:cpp
  - pushd . && if [ "$CXX" == "clang++" ]; then source "./update-clang.sh"; fi && popd

script:
  - clang --version
  - clang++ --version
  - gcc --version
  - g++ --version
  - cmake --version
  - bii --version

notifications:
  email: false
