language: c++
sudo: false
matrix:
  include:
    - os: osx
      compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise
          packages:
            - clang-3.7
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
cache:
  apt: true
  directories:
  - ".travis/cmake/build/install"

before_install:
  - if [ "$CC"  == "gcc"     ]; then export CC=gcc-5; fi
  - if [ "$CXX" == "g++"     ]; then export CXX=g++-5; fi
  - if [ "$CC"  == "clang"   ]; then export CC=clang-3.7; fi
  - if [ "$CXX" == "clang++" ]; then export CXX=clang++-3.7; fi
  - pushd . && source "./install-biicode.sh" && popd
  - pushd . && source "./update-cmake.sh"    && popd

script:
  - bii --version
  - cmake --version
  - $CC --version
  - $CXX --version

notifications:
  email: false
