language: c++
sudo: false
matrix:
  include:
    - os: osx
      compiler: clang
cache:
  apt: true
  directories:
  - "cache"

script:
  - ls -lahR
  - if [ ! -d "cache/test" ]; then mkdir -p "cache/test" && touch "cache/test/test.txt"; fi

notifications:
  email: false
