language: c++
compiler:
#  - clang
  - gcc

sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
cache:
  apt: true
  directories:
  - ".travis/cmake/build/install"

before_install:
  - if [ "$CC"  == "gcc" ]; then export CC=gcc-5; fi
  - if [ "$CXX" == "g++" ]; then export CXX=g++-5; fi
  - pushd . && source "./install-biicode.sh"  && popd
  - pushd . && source "./update-cmake.sh"  && popd
  - bii setup:cpp
  - pushd . && if [ "$CXX" == "clang++" ]; then source "./update-clang.sh"; fi && popd

script:
  - bii --version
  - cmake --version
  - $CC --version
  - $CXX --version

notifications:
  email: false
