language: c++
compiler:
  - clang
#  - gcc

sudo: false

before_install:
  - pushd . &&                                  source "./update-cmake.sh"     && popd
  - pushd . && if [ "$CXX" == "clang++" ]; then source "./update-clang.sh"; fi && popd
  - pushd . && if [ "$CXX" ==     "g++" ]; then source "./update-gcc.sh";   fi && popd
  - pushd . &&                                  source "./install-biicode.sh"  && popd

script:
  - clang --version
  - clang++ --version
  - gcc --version
  - g++ --version
  - cmake --version
  - bii --version

notifications:
  email: false
